# Generated by Django 4.2.14 on 2024-07-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
    ]
